tables ="""ACCOUNT_REPS
AEG_FEED_ZONES
AXSAUTH
AXS_EVENT_MAPPING
AXS_VENUE_MAPPING
COUNTRYINFO
CUSTOMERS
CUSTOMER_ADDRESS
CUSTOMER_FIELDS
CUSTOMER_FIELD_LISTS
CUSTOMER_PHONE
CUSTOMER_PHONE_TYPE
DIM_EVENT_META
EVENTS
EVENT_CATEGORY
INVENTORY
INVENTORY_SNAPSHOT
METHOD_OF_DELIVERY
METHOD_OF_DELIVERY_TYPE
METHOD_OF_PAYMENT_TYPE
OFFERS
OFFER_GROUPS
OFFER_GROUP_PRODUCTS
OFFER_LABEL
OFFER_METHOD_OF_DELIVERY
OFFER_OUTLETS
ONSALE_CALENDAR
ORDERS
ORDER_FEES
ORDER_FEE_COMP_TAX_COMP
ORDER_PRICE_COMPONENTS
ORDER_PRICE_COMP_TAX_COMP
ORDER_REFUNDS
ORDER_STATUS
ORDER_TAGS
ORDER_TICKETS
PAYMENTS
PAYMENT_DISTRIBUTIONS
PAYMENT_RESULT
PAYMENT_STATUS
PRICE_CHART
PRICE_CODES
PRICE_COMPONENTS
PRICE_LEVELS
PRICING_MODE
PRODUCTS
RESERVATIONS_SOLD
SCANNER_RESPONSE
SCANS
SEATS
SEAT_GROUPS
STATUS_CODES
STATUS_RESTRICTION_TYPE
US_ZIPCODES
VENUES
ZONES
ZONE_GLCODES"""

exclude = ['AEG_FEED_ZONES', 'AXS_EVENT_MAPPING', 'AXS_VENUE_MAPPING', 'COUNTRYINFO', 'CUSTOMER_PHONE_TYPE', 'DIM_EVENT_META', 'METHOD_OF_DELIVERY_TYPE', 'METHOD_OF_PAYMENT_TYPE', 'OFFER_LABEL', 'ORDER_STATUS', 'PAYMENT_RESULT', 'PAYMENT_STATUS', 'PRICING_MODE', 'SCANNER_RESPONSE', 'STATUS_RESTRICTION_TYPE', 'US_ZIPCODES', ]
for table in tables.split('\n'):
    if table not in exclude:
        print(f"SELECT '{table}',489512047, COUNT(*) from ANALYTICS.TICKETING_US.{table} where context_id = 489512047 union")
        # print(f"SELECT '{table}',707871657, COUNT(*) from ANALYTICS.TICKETING_US.{table} where context_id = 707871657 union")